apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb
    spec:
      containers:
        - args:
            - --max-allowed-packet=128M
            - --innodb-log-file-size=64M
          env:
            - name: MYSQL_DATABASE
              value: owncloud
            - name: MYSQL_PASSWORD
              value: owncloud
            - name: MYSQL_ROOT_PASSWORD
              value: owncloud
            - name: MYSQL_USER
              value: owncloud
          image: mariadb:10.5
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -u
                - root
                - --password=owncloud
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: owncloud-mariadb
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql
      restartPolicy: Always
      volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql
status: {}
